    // Datos de los cantos
const songs = [

    {id:1,title: "A la cena del Cordero", subtitle: "Himno lat. «Ad cenam Agni providi»", category: "Eleccion", moments: ["Pascua","Pentecostés","Laudes"], url: "/cantos/src/chtml/a/alacenadelcordero.html"},
    {id:2,title: "A la víctima pascual", subtitle: "Secuencia de Pascua - Himno lat. «Victimae paschall laudes» ", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Nuevo Testamento"], url: "/cantos/resucito/a/alavictimapascual.html"},
    {id:3,title: "A nadie demos ocasión de tropiezo", subtitle: "2ª Corintios 6,3ss", category: "Precatecumenado", moments: ["Nuevo Testamento"], url: "/cantos/resucito/a/anadiedemosocasiondetropiezo.html"},
    {id:4,title: "A ti levanto mis ojos", subtitle: "Salmo 123 (122)", category: "Precatecumenado", moments: ["Cuaresma","Antiguo Testamento"], url: "/cantos/src/chtml/a/atilevantomisojos.html"},
    {id:5,title: "A ti, Señor, en mi clamor imploro", subtitle: "Salmo 142 (141)", category: "Precatecumenado", moments: ["Cuaresma","Antiguo Testamento"], url: "/cantos/resucito/a/atisenorenmiclamorimploro.html"},
    {id:6,title: "A ti, Señor, levanto mi alma", subtitle: "Salmo 25 (24)", category: "Precatecumenado", moments: ["Cuaresma","Antiguo Testamento"], url: "/cantos/src/chtml/a/atisenorlevantomialma.html"},
    {id:7,title: "A ti, Señor, se debe la alabanza en Sión", subtitle: "Salmo 65 (64)", category: "Precatecumenado", moments: ["Cuaresma","Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/a/atisenorsedebelaalabanzaension.html"},
    {id:8,title: "Abbá, Padre", subtitle: "Romanos 8,15–17", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Entrada","Laudes","Nuevo Testamento"], url: "/cantos/src/chtml/a/abbapadre.html"},
    {id:9,title: "Abraham", subtitle: "Génesis 18,1–5 – Teofanía de Mambré", category: "Precatecumenado", moments: ["Entrada","Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/a/abraham.html"},
    {id:10,title: "Aclamaciones a la oración de los fieles", subtitle: "Respuestas a las oraciones de los fieles, Modelo I, II, III, IV", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/a/aclamacionesalaoraciondelosfieles.html"},
    {id:11,title: "Aclamad al Señor", subtitle: "Salmo 100 (99)", category: "Precatecumenado", moments: ["Entrada","Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/a/aclamadalsenor.html"},
    {id:12,title: "Adónde te escondiste, Amado", subtitle: "Cántico espiritual (San Juan de la Cruz) ", category: "Eleccion", moments: [""], url: "/cantos/src/chtml/a/adondeteescondisteamado.html"},
    {id:13,title: "Al despertar", subtitle: "Salmo 17 (16) ", category: "Precatecumenado", moments: ["Cuaresma","Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/a/aldespertar.html"},
    {id:14,title: "Alabad al Señor en el cielo", subtitle: "Salmo 148 ", category: "Precatecumenado", moments: ["Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/a/alabadalsenorenelcielo.html"},
    {id:15,title: "Alegría, ha nacido el salvador", subtitle: "Villancico (Kiko Argüello)", category: "Precatecumenado", moments: ["Adviento","Navidad","Niños"], url: "/cantos/src/chtml/a/alegriahanacidoelsalvador.html"},
    {id:16,title: "Aleluya interleccional", subtitle: "Modelo I, II, III", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/a/aleluyainterleccional.html"},
    {id:17,title: "Aleluya pascual", subtitle: "Apropiado para el tiempo Pascual", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/a/aleluyapascual.html"},
    {id:18,title: "Aleluya, alabad al Señor", subtitle: "Salmo 150", category: "Precatecumenado", moments: ["Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/a/aleluyaalabadalsenor.html"},
    {id:19,title: "Aleluya, bendecid al Señor", subtitle: "Salmo 1.34 (1.33) - Melodía hebraica", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Paz","Niños","Antiguo Testamento"], url: "/cantos/src/chtml/a/aleluyabendecidalsenor.html"},
    {id:20,title: "Aleluya, ya llegó el reino", subtitle: "Apocalipsis 19,6-9", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Laudes","Nuevo Testamento"], url: "/cantos/src/chtml/a/aleluyayallegoelreino.html"},
    {id:21,title: "Alzaos, puertas", subtitle: "Salmo 24 (23)", category: "Precatecumenado", moments: ["Entrada","Antiguo Testamento"], url: "/cantos/src/chtml/a/alzaospuertas.html"},
    {id:22,title: "Amén, amén, amén", subtitle: "Apocalipsis 7,12-14 ", category: "Precatecumenado", moments: ["Entrada","Nuevo Testamento"], url: "/cantos/src/chtml/a/amenamenamen.html"},
    {id:23,title: "Amo al Señor", subtitle: "Salmo 116 (114-115)", category: "Precatecumenado", moments: ["Cuaresma","Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/a/amoalsenor.html"},
    {id:24,title: "Antífona para el Evangelio", subtitle: "Tiempo de Cuaresma", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/a/antifonaparaelevangelio.html"},
    {id:25,title: "Aquedah", subtitle: "Gn 22,1-19 - Del Targum Neofiti sobre el sacrificio de Isaac", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Antiguo Testamento"], url: "/cantos/src/chtml/a/aquedah.html"},
    {id:26,title: "Así habla el amén", subtitle: "Ap 3,14-20", category: "Precatecumenado", moments: ["Cuaresma"], url: "/cantos/src/chtml/a/asihablaelamen.html"},
    {id:27,title: "Ave María I", subtitle: "Lc 1,28ss", category: "Precatecumenado", moments: ["Virgen","Nuevo Testamento"], url: "/cantos/src/chtml/a/avemariai.html"},
    {id:28,title: "Ave María II (1984)", subtitle: "Lc 1,28ss - 1984 ", category: "Precatecumenado", moments: ["Virgen","Nuevo Testamento"], url: "/cantos/src/chtml/a/avemariaii(1984).html"},
    {id:29,title: "Babilonia criminal", subtitle: "Sal 137 (136)", category: "Precatecumenado", moments: ["Cuaresma","Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/b/babiloniacriminal.html"},
    {id:30,title: "Balaam", subtitle: "Nm 23,7-24", category: "Precatecumenado", moments: ["Paz","Antiguo Testamento","Final"], url: "/cantos/src/chtml/b/balaam.html"},
    {id:31,title: "Bendeciré al Señor en todo tiempo", subtitle: "Sal 34 (33)", category: "Precatecumenado", moments: ["Cuaresma","Comunión","Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/b/bendecirealsenorentodotiempo.html"},
    {id:32,title: "Bendice, alma mía, a Yahveh", subtitle: "Sal 103 (102)", category: "Precatecumenado", moments: ["Cuaresma","Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/b/bendicealmamiaayahveh.html"},
    {id:33,title: "Bendición del agua", subtitle: "De la liturgia bautismal de la Vigilia pascual", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/b/bendiciondelagua.html"},
    {id:34,title: "Bendita eres tú, María", subtitle: "Lucas 1,42-45", category: "Precatecumenado", moments: ["Entrada","Virgen","Nuevo Testamento"], url: "/cantos/src/chtml/b/benditaerestumaria.html"},
    {id:35,title: "Bendito eres, Señor", subtitle: "Daniel 3,52-57", category: "Precatecumenado", moments: ["Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/b/benditoeressenor.html"},
    {id:36,title: "Bendito sea Dios", subtitle: "Efesios 1,3-13", category: "Precatecumenado", moments: ["Adviento","Navidad"], url: "/cantos/src/chtml/b/benditoseadios.html"},
    {id:37,title: "Benedictus", subtitle: "Lucas 1,67-80", category: "Precatecumenado", moments: ["Laudes","Nuevo Testamento"], url: "/cantos/src/chtml/b/benedictus.html"},
    {id:38,title: "Cantad a Dios", subtitle: "Salmo 67 (68) 2.4-7", category: "Precatecumenado", moments: ["Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/c/cantadadios.html"},
    {id:39,title: "Cantad al Señor", subtitle: "Salmo 117 (116)", category: "Precatecumenado", moments: ["Entrada","Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/c/cantadalsenor.html"},
    {id:40,title: "Cántico de los tres jóvenes", subtitle: "Daniel 3,57-58", category: "Precatecumenado", moments: ["Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/c/canticodelostresjovenes.html"},
    {id:41,title: "Canto de Moisés", subtitle: "Éxodo 15,1-18", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Antiguo Testamento"], url: "/cantos/src/chtml/c/cantodemoises.html"},
    {id:42,title: "Caritas Christi urget nos", subtitle: "2ª Corintios 5,14.15.17.21", category: "Precatecumenado", moments: ["Cuaresma","Nuevo Testamento"], url: "/cantos/src/chtml/c/caritaschristiurgetnos.html"},
    {id:43,title: "Carmen 63", subtitle: "(Rabindranath Tagore)*", category: "Precatecumenado", moments: ["Comunión","Final"], url: "/cantos/src/chtml/c/carmen63.html"},
    {id:44,title: "Celebración penitencial (Bendición penitencial )", subtitle: "Acción de gracias", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/c/celebracionpenitencial(bendicionpenitencial).html"},
    {id:45,title: "Como condenados a muerte", subtitle: "1ª Corintios 4,9-13", category: "Precatecumenado", moments: ["Nuevo Testamento"], url: "/cantos/src/chtml/c/comocondenadosamuerte.html"},
    {id:46,title: "Como destila la miel", subtitle: "Oda XL de Salomón", category: "Eleccion", moments: [""], url: "/cantos/src/chtml/c/comodestilalamiel.html"},
    {id:47,title: "Como el impulso que siente la ira", subtitle: "Oda VII de Salomón", category: "Catecumenado", moments: ["Laudes"], url: "/cantos/src/chtml/c/comoelimpulsoquesientelaira.html"},
    {id:48,title: "Cómo es maravilloso", subtitle: "Salmo 133 (132)", category: "Precatecumenado", moments: ["Paz","Antiguo Testamento"], url: "/cantos/src/chtml/c/comoesmaravilloso.html"},
    {id:49,title: "Como la cierva", subtitle: "Salmo 42-43 (41-42)", category: "Precatecumenado", moments: ["Cuaresma","Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/c/comolacierva.html"},
    {id:50,title: "Como lirio entre los cardos", subtitle: "Cantar de los cantares 1,13ss ", category: "Eleccion", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/c/comolirioentreloscardos.html"},
    {id:51,title: "Como oveja que ve", subtitle: "Kontáklon (Romano el Meloda)", category: "Precatecumenado", moments: ["Cuaresma","Pascua","Pentecostés","Virgen","Pan"], url: "/cantos/src/chtml/c/comoovejaqueve.html"},
    {id:52,title: "Consolad a mi pueblo", subtitle: "Isaías 40,1-11 - Melodía hebraica ", category: "Precatecumenado", moments: ["Adviento","Navidad","Entrada","Paz","Antiguo Testamento","Final"], url: "/cantos/src/chtml/c/consoladamipueblo.html"},
    {id:53,title: "Cordero de Dios", subtitle: "Después de la consagración", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/c/corderodedios.html"},
    {id:54,title: "Credo", subtitle: "Símbolo Apostólico", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/c/credo.html"},
    {id:55,title: "Cristo es la luz", subtitle: "Himno - Juan 8,12; 14,6", category: "Precatecumenado", moments: ["Pascua","Pentecostés"], url: "/cantos/src/chtml/c/cristoeslaluz.html"},
    {id:56,title: "Cuando dormía", subtitle: "Cantar de los Cantares 5,2ss ", category: "Catecumenado", moments: ["Comunión","Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/c/cuandodormia.html"},
    {id:57,title: "Cuando el Señor", subtitle: "Salmo 126 (125)", category: "Precatecumenado", moments: ["Adviento","Navidad","Cuaresma","Entrada","Antiguo Testamento"], url: "/cantos/src/chtml/c/cuandoelsenor.html"},
    {id:58,title: "Cuando Israel salió de Egipto", subtitle: "Salmo 114 (113)", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/c/cuandoisraelsaliodeegipto.html"},
    {id:59,title: "Dayenú", subtitle: "De la Hagadá de Pésaj hebrea", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Paz"], url: "/cantos/src/chtml/d/dayenu.html"},
    {id:60,title: "De Profundis", subtitle: "Salmo 130 (129)", category: "Precatecumenado", moments: ["Adviento","Navidad","Cuaresma","Antiguo Testamento"], url: "/cantos/src/chtml/d/deprofundis.html"},
    {id:61,title: "Débora", subtitle: "Jueces 5", category: "Catecumenado", moments: ["Virgen","Antiguo Testamento"], url: "/cantos/src/chtml/d/debora.html"},
    {id:62,title: "Decidle a los de corazón cansado", subtitle: "Isaías 35,4ss", category: "Precatecumenado", moments: ["Adviento","Navidad","Cuaresma","Entrada","Antiguo Testamento"], url: "/cantos/src/chtml/d/decidlealosdecorazoncansado.html"},
    {id:63,title: "Delante de los ángeles", subtitle: "Salmo 138 (137)", category: "Precatecumenado", moments: ["Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/d/delantedelosangeles.html"},
    {id:64,title: "Día de reposo", subtitle: "Juan 8,52", category: "Precatecumenado", moments: ["Nuevo Testamento","Final"], url: "/cantos/src/chtml/d/diadereposo.html"},
    {id:65,title: "Dice el Señor a mi Señor", subtitle: "Salmo 110 (109)", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/d/diceelsenoramisenor.html"},
    {id:66,title: "Dichoso el hombre", subtitle: "Salmo 1", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/d/dichosoelhombre.html"},
    {id:67,title: "El combate escatológico", subtitle: "Apocalipsis 19,11-20", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Entrada","Nuevo Testamento"], url: "/cantos/src/chtml/e/elcombateescatologico.html"},
    {id:68,title: "El Espíritu del Señor está sobre mí", subtitle: "Lucas 4,18 – Isaías 61,1-3", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Entrada","Comunión","Laudes","Nuevo Testamento","Antiguo Testamento"], url: "/cantos/src/chtml/e/elespiritudelsenorestasobremi.html"},
    {id:69,title: "El jacal de los pastores", subtitle: "Cantar de los Cantares 1,2-8", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Comunión","Antiguo Testamento"], url: "/cantos/src/chtml/e/eljacaldelospastores.html"},
    {id:70,title: "El lagarero", subtitle: "Isaías 63,1-6", category: "Precatecumenado", moments: ["Pan","Antiguo Testamento"], url: "/cantos/src/chtml/e/ellagarero.html"},
    {id:71,title: "El Mesías león", subtitle: "Comentario al Apocalipsis (Victorino de Pettau)", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Pan"], url: "/cantos/src/chtml/e/elmesiasleon.html"},
    {id:72,title: "El mismo Dios", subtitle: "2 Corintios 4,6-12", category: "Catecumenado", moments: ["Comunión","Nuevo Testamento"], url: "/cantos/src/chtml/e/elmismodios.html"},
    {id:73,title: "El necio piensa que Dios no existe", subtitle: "Salmo 14 (13)", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/e/elneciopiensaquediosnoexiste.html"},
    {id:74,title: "El pueblo que caminaba en las tinieblas", subtitle: "Isaías 9,1-5", category: "Precatecumenado", moments: ["Adviento","Navidad","Antiguo Testamento"], url: "/cantos/src/chtml/e/elpuebloquecaminabaenlastinieblas.html"},
    {id:75,title: "El sembrador", subtitle: "Marcos 4,3ss", category: "Catecumenado", moments: ["Nuevo Testamento"], url: "/cantos/src/chtml/e/elsembrador.html"},
    {id:76,title: "El Señor anuncia una noticia", subtitle: "Salmo 68 (67)", category: "Precatecumenado", moments: ["Entrada","Antiguo Testamento"], url: "/cantos/src/chtml/e/elsenoranunciaunanoticia.html"},
    {id:77,title: "El Señor es mi pastor", subtitle: "Salmo 23 (22)", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Comunión","Antiguo Testamento"], url: "/cantos/src/chtml/e/elsenoresmipastor.html"},
    {id:78,title: "El Señor me ha dado", subtitle: "Isaías 50,4-10  - Tercer canto del Siervo de Yahveh", category: "Precatecumenado", moments: ["Pan","Antiguo Testamento"], url: "/cantos/src/chtml/e/elsenormehadado.html"},
    {id:79,title: "Elí, Elí, lamá sabactaní", subtitle: "Salmo 22 (21)", category: "Precatecumenado", moments: ["Adviento","Navidad","Cuaresma","Antiguo Testamento"], url: "/cantos/src/chtml/e/elielilamasabactani.html"},
    {id:80,title: "En medio de aquel gentío", subtitle: "Lucas 8,42b-48", category: "Precatecumenado", moments: ["Comunión","Nuevo Testamento"], url: "/cantos/src/chtml/e/enmediodeaquelgentio.html"},
    {id:81,title: "En una noche oscura", subtitle: "Subida al Monte Carmelo – San Juan de la Cruz", category: "Precatecumenado", moments: [""], url: "/cantos/src/chtml/e/enunanocheoscura.html"},
    {id:82,title: "Eres digno de tomar el libro", subtitle: "Apocalipsis 5,9ss", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Pan","Laudes","Nuevo Testamento"], url: "/cantos/src/chtml/e/eresdignodetomarellibro.html"},
    {id:83,title: "Eres hermoso", subtitle: "Salmo 45 (44) ", category: "Precatecumenado", moments: ["Comunión","Antiguo Testamento","Final"], url: "/cantos/src/chtml/e/ereshermoso.html"},
    {id:84,title: "Es paciente", subtitle: "Himno al Espíritu Santo (Kiko Argüello) ", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Entrada","Comunión"], url: "/cantos/src/chtml/e/espaciente.html"},
    {id:85,title: "Escóndeme en lo oculto de tu tienda", subtitle: "Salmo 27 (26)", category: "Precatecumenado", moments: ["Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/e/escondemeenloocultodetutienda.html"},
    {id:86,title: "Escuchad, islas lejanas", subtitle: "Isaias 49,1-16 - Segundo canto de Siervo de Yahveh", category: "Precatecumenado", moments: ["Adviento","Navidad","Entrada","Comunión","Antiguo Testamento"], url: "/cantos/src/chtml/e/escuchadislaslejanas.html"},
    {id:87,title: "Éste es el día en que actuó el Señor", subtitle: "Sal 118 (117)", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/é/esteeseldiaenqueactuoelsenor.html"},
    {id:88,title: "Este es el mandamiento mío", subtitle: "Jn 15,12ss", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Nuevo Testamento"], url: "/cantos/src/chtml/e/esteeselmandamientomio.html"},
    {id:89,title: "Evenu shalom alejem", subtitle: "Melodía hebraica", category: "Precatecumenado", moments: ["Paz"], url: "/cantos/src/chtml/e/evenushalomalejem.html"},
    {id:90,title: "Extiendo mis manos", subtitle: "Oda XXVII de Salomón", category: "Precatecumenado", moments: ["Adviento","Navidad","Cuaresma","Pan"], url: "/cantos/src/chtml/e/extiendomismanos.html"},
    {id:91,title: "Exultad, justos, en el Señor", subtitle: "Sal 33 (32)", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Entrada","Comunión","Antiguo Testamento"], url: "/cantos/src/chtml/e/exultadjustosenelsenor.html"},
    {id:92,title: "Felicidad para el hombre", subtitle: "Sal 128 (127)", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/f/felicidadparaelhombre.html"},
    {id:93,title: "Gloria a Dios en lo alto del cielo", subtitle: "Himno Litúrgico", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/g/gloriaadiosenloaltodelcielo.html"},
    {id:94,title: "Gracias a Yahveh", subtitle: "Sal 136 (135) - Melodía hebraica", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Paz","Comunión","Antiguo Testamento","Final"], url: "/cantos/src/chtml/g/graciasayahveh.html"},
    {id:95,title: "Gritad jubilosos", subtitle: "Isaías 12,1ss", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Comunión","Antiguo Testamento","Final"], url: "/cantos/src/chtml/g/gritadjubilosos.html"},
    {id:96,title: "Hacia ti, morada santa", subtitle: "Himno procesional eucarístico (Kiko Argüello)", category: "Precatecumenado", moments: ["Entrada"], url: "/cantos/src/chtml/h/haciatimoradasanta.html"},
    {id:97,title: "Hasta cuándo", subtitle: "Sal 13 (12)", category: "Precatecumenado", moments: ["Cuaresma","Antiguo Testamento"], url: "/cantos/src/chtml/h/hastacuando.html"},
    {id:98,title: "He aquí mi siervo", subtitle: "Isaías 42,1-4; Mateo 12,18-21 - Primer canto de Siervo de Yahveh", category: "Precatecumenado", moments: ["Cuaresma","Pan","Antiguo Testamento"], url: "/cantos/src/chtml/h/heaquimisiervo.html"},
    {id:99,title: "He aquí que nuestro espejo es el Señor", subtitle: "Oda XIII de Salomón", category: "Catecumenado", moments: ["Cuaresma","Laudes"], url: "/cantos/src/chtml/h/heaquiquenuestroespejoeselsenor.html"},
    {id:100,title: "He aquí que vengo presto", subtitle: "Apocalipsis 22,12-16", category: "Precatecumenado", moments: ["Adviento","Navidad","Entrada","Nuevo Testamento"], url: "/cantos/src/chtml/h/heaquiquevengopresto.html"},
    {id:101,title: "He esperado en el Señor", subtitle: "Salmo 40 (39)", category: "Precatecumenado", moments: ["Cuaresma","Antiguo Testamento"], url: "/cantos/src/chtml/h/heesperadoenelsenor.html"},
    {id:102,title: "Hermosa eres, amiga mía", subtitle: "Cantar de los cantares 6-7", category: "Eleccion", moments: ["Pascua","Pentecostés","Antiguo Testamento"], url: "/cantos/src/chtml/h/hermosaeresamigamia.html"},
    {id:103,title: "Hijas de Jerusalén", subtitle: "Lucas 23,28-46", category: "Precatecumenado", moments: ["Cuaresma","Pan","Nuevo Testamento"], url: "/cantos/src/chtml/h/hijasdejerusalen.html"},
    {id:104,title: "Himno a Cristo luz", subtitle: "Himno vespertino (San Gregorio Nacianceno)", category: "Precatecumenado", moments: ["Pascua","Pentecostés"], url: "/cantos/src/chtml/h/himnoacristoluz.html"},
    {id:105,title: "Himno a la caridad", subtitle: "1 Corintios 13,1-7", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Comunión","Nuevo Testamento"], url: "/cantos/src/chtml/h/himnoalacaridad.html"},
    {id:106,title: "Himno a la cruz gloriosa", subtitle: "Homilía La Santa Pascua (Anónimo s. II)", category: "Catecumenado", moments: ["Laudes"], url: "/cantos/src/chtml/h/himnoalacruzgloriosa.html"},
    {id:107,title: "Himno a la kenosis", subtitle: "Filipenses 2,1-11", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Pan","Nuevo Testamento"], url: "/cantos/src/chtml/h/himnoalakenosis.html"},
    {id:108,title: "Himno de Adviento", subtitle: "Himno lat. «Vox clara ecce Intonat»", category: "Precatecumenado", moments: ["Adviento","Navidad"], url: "/cantos/src/chtml/h/himnodeadviento.html"},
    {id:109,title: "Himno de la Ascensión", subtitle: "Himno de Laudes del tiempo Pascual, de la Ascensión a Pentecostés  / Himno de la liturgia de las horas ", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Laudes"], url: "/cantos/src/chtml/h/himnodelaascension.html"},
    {id:110,title: "Himno de Pascua", subtitle: "Himno lat. «Aurora lucis rutiiat»", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Laudes"], url: "/cantos/src/chtml/h/himnodepascua.html"},
    {id:111,title: "Huye, amado mío", subtitle: "Cantar de los Cantares 8,10-14", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Comunión","Antiguo Testamento","Final"], url: "/cantos/src/chtml/h/huyeamadomio.html"},
    {id:112,title: "Id y anunciad a mis hermanos", subtitle: "Mateo 28,10.16-20", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Nuevo Testamento","Final"], url: "/cantos/src/chtml/i/idyanunciadamishermanos.html"},
    {id:113,title: "Improperios", subtitle: "Adoración de la santa Cruz el Viernes santo", category: "Precatecumenado", moments: ["Cuaresma","Pan"], url: "/cantos/src/chtml/i/improperios.html"},
    {id:114,title: "Jacob", subtitle: "Genesis 32,23-29 ", category: "Catecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/j/jacob.html"},
    {id:115,title: "Jerusalén reconstruida", subtitle: "Tobias 13,11-17", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Paz","Antiguo Testamento"], url: "/cantos/src/chtml/j/jerusalenreconstruida.html"},
    {id:116,title: "Jesús recorría todas las ciudades", subtitle: "Mateo 9,35ss; 10 ", category: "Precatecumenado", moments: ["Nuevo Testamento"], url: "/cantos/src/chtml/j/jesusrecorriatodaslasciudades.html"},
    {id:117,title: "La cordera de Dios", subtitle: "Mateo 1,18s; 2,13s.18", category: "Precatecumenado", moments: ["Adviento","Navidad","Virgen","Nuevo Testamento"], url: "/cantos/src/chtml/l/lacorderadedios.html"},
    {id:118,title: "La espada", subtitle: "Ezequiel 21,14-22", category: "Precatecumenado", moments: ["Cuaresma","Virgen"], url: "/cantos/src/chtml/l/laespada.html"},
    {id:119,title: "La marcha es dura", subtitle: "Espiritual negro «Go down, Moses»", category: "Precatecumenado", moments: ["Cuaresma"], url: "/cantos/src/chtml/l/lamarchaesdura.html"},
    {id:120,title: "La paloma voló", subtitle: "Oda XXIV de Salomón", category: "Eleccion", moments: ["Laudes"], url: "/cantos/src/chtml/l/lapalomavolo.html"},
    {id:121,title: "La Salve", subtitle: "Himno lat. «Salve Regina»", category: "Precatecumenado", moments: ["Cuaresma","Virgen"], url: "/cantos/src/chtml/l/lasalve.html"},
    {id:122,title: "La siega de las naciones", subtitle: "Juan 4,31-38", category: "Precatecumenado", moments: ["Nuevo Testamento","Final"], url: "/cantos/src/chtml/l/lasiegadelasnaciones.html"},
    {id:123,title: "La voz de mi amado", subtitle: "Cantar de los Cantares 2,8-17", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Comunión","Antiguo Testamento"], url: "/cantos/src/chtml/l/lavozdemiamado.html"},
    {id:124,title: "Las armas de la luz", subtitle: "cf Efesios 6,11.ss", category: "Precatecumenado", moments: ["Adviento","Navidad","Cuaresma","Laudes","Nuevo Testamento"], url: "/cantos/src/chtml/l/lasarmasdelaluz.html"},
    {id:125,title: "Lauda Sión", subtitle: "Secuencia del Corpus Christi (Santo Tomas de Aquino) ", category: "Precatecumenado", moments: ["Pascua","Pentecostés"], url: "/cantos/src/chtml/l/laudasion.html"},
    {id:126,title: "Letanías de los santos", subtitle: "De la liturgia bautismal de la Vigilia pascual", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/l/letaniasdelossantos.html"},
    {id:127,title: "Letanías penitenciales I", subtitle: "Letanía para la Celebración Penitencial – modelo abreviado", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/l/letaniaspenitencialesi.html"},
    {id:128,title: "Letanías penitenciales II", subtitle: "Letanía para la Celebración Penitencial", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/l/letaniaspenitencialesii.html"},
    {id:129,title: "Levanto mis ojos a los montes", subtitle: "Sal 121 (120)", category: "Precatecumenado", moments: ["Cuaresma","Entrada","Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/l/levantomisojosalosmontes.html"},
    {id:130,title: "Llegue hasta tu presencia mi clamor", subtitle: "Sal 119 (118)", category: "Precatecumenado", moments: ["Adviento","Navidad","Cuaresma","Entrada","Laudes"], url: "/cantos/src/chtml/l/lleguehastatupresenciamiclamor.html"},
    {id:131,title: "Llévame al cielo", subtitle: "Filipenses 1,23", category: "Precatecumenado", moments: ["Adviento","Navidad","Pascua","Pentecostés","Nuevo Testamento","Final"], url: "/cantos/src/chtml/l/llevamealcielo.html"},
    {id:132,title: "Magníficat", subtitle: "Lucas 1,46-55", category: "Precatecumenado", moments: ["Virgen","Laudes","Nuevo Testamento"], url: "/cantos/src/chtml/m/magnificat.html"},
    {id:133,title: "María de Jasna Göra", subtitle: "Himno a la Virgen de Jasna Göra, Częstochowa Polonia (Kiko Argüello) ", category: "Precatecumenado", moments: ["Virgen"], url: "/cantos/src/chtml/m/mariadejasnagöra.html"},
    {id:134,title: "María, casa de bendición", subtitle: "Juan 2,1–11 – Las Bodas de Caná", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Virgen","Comunión","Nuevo Testamento"], url: "/cantos/src/chtml/m/mariacasadebendicion.html"},
    {id:135,title: "María, madre de la Iglesia", subtitle: "Juan 19,26-34", category: "Precatecumenado", moments: ["Cuaresma","Virgen","Pan","Nuevo Testamento"], url: "/cantos/src/chtml/m/mariamadredelaiglesia.html"},
    {id:136,title: "María, madre del camino ardiente", subtitle: "Himno a la Virgen del Tercer Milenio (Kiko Argüello)", category: "Precatecumenado", moments: ["Adviento","Navidad","Virgen"], url: "/cantos/src/chtml/m/mariamadredelcaminoardiente.html"},
    {id:137,title: "María, pequeña María", subtitle: "Himno a la Virgen María (Kiko Argüello)", category: "Precatecumenado", moments: ["Cuaresma","Virgen"], url: "/cantos/src/chtml/m/mariapequenamaria.html"},
    {id:138,title: "Me enseñarás el camino de la vida", subtitle: "Sal 16 (15)", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Entrada","Antiguo Testamento"], url: "/cantos/src/chtml/m/meensenaraselcaminodelavida.html"},
    {id:139,title: "Me has seducido, Señor", subtitle: "Jeremias 20,7-18", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/m/mehasseducidosenor.html"},
    {id:140,title: "Me robaste el corazón", subtitle: "Cantar de los cantares 4,9 - 5,1", category: "Eleccion", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/m/merobasteelcorazon.html"},
    {id:141,title: "Mirad qué estupendo", subtitle: "Sal 133 (132)", category: "Precatecumenado", moments: ["Paz","Antiguo Testamento"], url: "/cantos/src/chtml/m/miradqueestupendo.html"},
    {id:142,title: "Misericordia mía, misericordia", subtitle: "Sal 51 (50)", category: "Precatecumenado", moments: ["Cuaresma","Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/m/misericordiamiamisericordia.html"},
    {id:143,title: "Misericordia, Dios mío", subtitle: "Sal 51(50)", category: "Precatecumenado", moments: ["Cuaresma"], url: "/cantos/src/chtml/m/misericordiadiosmio.html"},
    {id:144,title: "Mucho me han perseguido", subtitle: "Sal 129 (128)", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/m/muchomehanperseguido.html"},
    {id:145,title: "Ninguno puede servir a dos señores", subtitle: "Mateo 6,24-33 ", category: "Catecumenado", moments: ["Nuevo Testamento"], url: "/cantos/src/chtml/n/ningunopuedeserviradossenores.html"},
    {id:146,title: "No está aquí, resucitó", subtitle: "Mateo 28,1-8", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Nuevo Testamento"], url: "/cantos/src/chtml/n/noestaaquiresucito.html"},
    {id:147,title: "No hay en él parecer", subtitle: "Isaías 53,2ss - Cuarto canto del Siervo de Yahveh", category: "Precatecumenado", moments: ["Pan","Antiguo Testamento"], url: "/cantos/src/chtml/n/nohayenelparecer.html"},
    {id:148,title: "No resistáis al mal", subtitle: "Mateo 5,38ss", category: "Catecumenado", moments: ["Nuevo Testamento"], url: "/cantos/src/chtml/n/noresistaisalmal.html"},
    {id:149,title: "No sufras por los malvados", subtitle: "Sal 37 (36)", category: "Catecumenado", moments: ["Cuaresma","Antiguo Testamento"], url: "/cantos/src/chtml/n/nosufrasporlosmalvados.html"},
    {id:150,title: "Noli me tangere", subtitle: "Juan 20,15-17", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Nuevo Testamento"], url: "/cantos/src/chtml/n/nolimetangere.html"},
    {id:151,title: "Oh cielos, lloved de lo alto", subtitle: "Isaías 45,8", category: "Precatecumenado", moments: ["Adviento","Navidad"], url: "/cantos/src/chtml/o/ohcieloslloveddeloalto.html"},
    {id:152,title: "Oh Dios, por tu nombre sálvame", subtitle: "Sal 54 (53)", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/o/ohdiosportunombresalvame.html"},
    {id:153,title: "Oh Dios, tú eres mi Dios", subtitle: "Sal 63 (62)", category: "Precatecumenado", moments: ["Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/o/ohdiostueresmidios.html"},
    {id:154,title: "Oh Jesús, amor mío", subtitle: "(Kiko Argüello)", category: "Precatecumenado", moments: ["Cuaresma","Pan"], url: "/cantos/src/chtml/o/ohjesusamormio.html"},
    {id:155,title: "Oh muerte, ¿dónde está tu victoria?", subtitle: "1 Corintios 15", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Comunión","Nuevo Testamento"], url: "/cantos/src/chtml/o/ohmuertedondeestatuvictoria.html"},
    {id:156,title: "Oh Señor, mi corazón ya no es ambicioso", subtitle: "Sal 131 (130)", category: "Catecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/o/ohsenormicorazonyanoesambicioso.html"},
    {id:157,title: "Oh Señor, nuestro Dios", subtitle: "Salmo 8", category: "Precatecumenado", moments: ["Entrada","Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/o/ohsenornuestrodios.html"},
    {id:158,title: "Os tomaré de entre las naciones", subtitle: "Ezequiel 36,24-28", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Entrada","Antiguo Testamento"], url: "/cantos/src/chtml/o/ostomaredeentrelasnaciones.html"},
    {id:159,title: "Padre nuestro", subtitle: "Tiempo de la Elección", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/p/padrenuestro.html"},
    {id:160,title: "Paloma incorrupta", subtitle: "Kontákion (Romano el Meloda)", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Virgen"], url: "/cantos/src/chtml/p/palomaincorrupta.html"},
    {id:161,title: "Pentecostés", subtitle: "Hchos de los Apostoles 2,1-13 ", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Comunión"], url: "/cantos/src/chtml/p/pentecostes.html"},
    {id:162,title: "Plegaria Eucarística II – Modelo I", subtitle: "Modelo I", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/p/plegariaeucaristicaii–modeloi.html"},
    {id:163,title: "Plegaria Eucarística II – Modelo II (1987)", subtitle: "Modelo II (1987)", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/p/plegariaeucaristicaii–modeloii(1987).html"},
    {id:164,title: "Plegaria Eucarística IV – (1988)", subtitle: "(1988)", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/p/plegariaeucaristicaiv–(1988).html"},
    {id:165,title: "Por el amor de mis amigos", subtitle: "Sal 122 (121) - Melodía hebraica ", category: "Precatecumenado", moments: ["Paz","Antiguo Testamento"], url: "/cantos/src/chtml/p/porelamordemisamigos.html"},
    {id:166,title: "Por qué esta noche es diferente", subtitle: "Haggadá de Pesaj - Melodía hebraica", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Niños"], url: "/cantos/src/chtml/p/porqueestanocheesdiferente.html"},
    {id:167,title: "Por qué las gentes conjuran", subtitle: "Salmo 2", category: "Precatecumenado", moments: ["Cuaresma","Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/p/porquelasgentesconjuran.html"},
    {id:168,title: "Porque mi yugo es suave", subtitle: "Mateo 11,28ss", category: "Precatecumenado", moments: ["Laudes","Nuevo Testamento"], url: "/cantos/src/chtml/p/porquemiyugoessuave.html"},
    {id:169,title: "Prefacio para Adviento y Navidad", subtitle: "Prefacio IV de Adviento*", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/p/prefacioparaadvientoynavidad.html"},
    {id:170,title: "Prefacio para el tiempo Pascual", subtitle: "Prefacio I de Pascua*", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/p/prefacioparaeltiempopascual.html"},
    {id:171,title: "Pregón Pascual", subtitle: "«Exsultet»", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/p/pregonpascual.html"},
    {id:172,title: "Qué amables son tus moradas", subtitle: "Sal 84 (83)", category: "Precatecumenado", moments: ["Cuaresma","Entrada","Antiguo Testamento"], url: "/cantos/src/chtml/q/queamablessontusmoradas.html"},
    {id:173,title: "Qué estupendo, qué alegría", subtitle: "Sal 133 (132)", category: "Precatecumenado", moments: ["Paz","Antiguo Testamento"], url: "/cantos/src/chtml/q/queestupendoquealegria.html"},
    {id:174,title: "Quién es ésta que sube del desierto", subtitle: "Cantar de los Cantares 8,5-7", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Comunión","Antiguo Testamento","Final"], url: "/cantos/src/chtml/q/quienesestaquesubedeldesierto.html"},
    {id:175,title: "Quién nos separará", subtitle: "Romanos 8,34-39", category: "Precatecumenado", moments: ["Cuaresma","Comunión","Laudes","Nuevo Testamento"], url: "/cantos/src/chtml/q/quiennosseparara.html"},
    {id:176,title: "Quiero andar, madre, a Jerusalén", subtitle: "Canto sefardí", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Final"], url: "/cantos/src/chtml/q/quieroandarmadreajerusalen.html"},
    {id:177,title: "Quiero cantar", subtitle: "Sal 57 (56)", category: "Precatecumenado", moments: ["Cuaresma","Antiguo Testamento"], url: "/cantos/src/chtml/q/quierocantar.html"},
    {id:178,title: "Resucitó", subtitle: "(Kiko Argüello)", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Comunión"], url: "/cantos/src/chtml/r/resucito.html"},
    {id:179,title: "Resurrexit", subtitle: "Juan 11,25s", category: "Precatecumenado", moments: ["Pascua","Pentecostés"], url: "/cantos/src/chtml/r/resurrexit.html"},
    {id:180,title: "Salmodia para el evangelio", subtitle: "Juan 3,11-20 ", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/s/salmodiaparaelevangelio.html"},
    {id:181,title: "Salmodia para el rosario", subtitle: "Oración", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/s/salmodiaparaelrosario.html"},
    {id:182,title: "Salmodia para el Salmo responsorial", subtitle: "Modelo I, II, III", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/s/salmodiaparaelsalmoresponsorial.html"},
    {id:183,title: "Salmodias para la oración de los fieles", subtitle: "Para las solemnidades", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/s/salmodiasparalaoraciondelosfieles.html"},
    {id:184,title: "Salmodias para laudes", subtitle: "Modelo I, II, III, IV, V", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/s/salmodiasparalaudes.html"},
    {id:185,title: "Salve, reina de los cielos", subtitle: "Himno lat. «Ave, Regina Caelorum»", category: "Precatecumenado", moments: ["Virgen"], url: "/cantos/src/chtml/s/salvereinadeloscielos.html"},
    {id:186,title: "Santo 1982", subtitle: "Palomeras 65", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/s/santo1982.html"},
    {id:187,title: "Santo 1988", subtitle: "Melodía hebraica ", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/s/santo1988.html"},
    {id:188,title: "Santo hebreo", subtitle: "Palestina 74", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/s/santohebreo.html"},
    {id:189,title: "Santo Palestina 74", subtitle: "Roma 77", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/s/santopalestina74.html"},
    {id:190,title: "Santo Palomeras 65", subtitle: "1982", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/s/santopalomeras65.html"},
    {id:191,title: "Santo Roma 77", subtitle: "1988", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/s/santoroma77.html"},
    {id:192,title: "Se encontraron dos ángeles", subtitle: "Melodía hebraica", category: "Precatecumenado", moments: ["Paz","Niños"], url: "/cantos/src/chtml/s/seencontrarondosangeles.html"},
    {id:193,title: "Señor, ayúdame a no dudar de ti", subtitle: "(Kiko Argüello)", category: "Precatecumenado", moments: ["Cuaresma","Laudes"], url: "/cantos/src/chtml/s/senorayudameanodudardeti.html"},
    {id:194,title: "Señor, no me corrijas en tu cólera", subtitle: "Salmo 6", category: "Precatecumenado", moments: ["Cuaresma","Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/s/senornomecorrijasentucolera.html"},
    {id:195,title: "Señor, tú me escrutas y conoces", subtitle: "Sal 139 (138)", category: "Catecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/s/senortumeescrutasyconoces.html"},
    {id:196,title: "Sermón de la montaña", subtitle: "Lucas 6,20-38", category: "Precatecumenado", moments: ["Nuevo Testamento"], url: "/cantos/src/chtml/s/sermondelamontana.html"},
    {id:197,title: "Shemá Israel", subtitle: "Dt 6,4-9", category: "Catecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/s/shemaisrael.html"},
    {id:198,title: "Shlom lej Mariam", subtitle: "Ave María en arameo antiguo", category: "Precatecumenado", moments: ["Virgen"], url: "/cantos/src/chtml/s/shlomlejmariam.html"},
    {id:199,title: "Si el Señor no construye la casa", subtitle: "Sal 127 (126)", category: "Precatecumenado", moments: ["Entrada","Antiguo Testamento"], url: "/cantos/src/chtml/s/sielsenornoconstruyelacasa.html"},
    {id:200,title: "Si habéis resucitado con Cristo", subtitle: "Colosense 3,1-4", category: "Precatecumenado", moments: [""], url: "/cantos/src/chtml/s/sihabeisresucitadoconcristo.html"},
    {id:201,title: "Si hoy escucháis su voz", subtitle: "Sal 95 (94)", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/s/sihoyescuchaissuvoz.html"},
    {id:202,title: "Si me he refugiado en el Señor", subtitle: "Sal 11(10)", category: "Precatecumenado", moments: ["Cuaresma","Antiguo Testamento"], url: "/cantos/src/chtml/s/simeherefugiadoenelsenor.html"},
    {id:203,title: "Siéntate solitario y silencioso", subtitle: "Lamentaciones 3", category: "Catecumenado", moments: ["Cuaresma","Antiguo Testamento"], url: "/cantos/src/chtml/s/sientatesolitarioysilencioso.html"},
    {id:204,title: "Sión, madre de todos los pueblos", subtitle: "Sal 87 (86)", category: "Precatecumenado", moments: ["Virgen","Antiguo Testamento","Final"], url: "/cantos/src/chtml/s/sionmadredetodoslospueblos.html"},
    {id:205,title: "Sola a Solo", subtitle: "(Kiko Argüello)", category: "Precatecumenado", moments: ["Cuaresma","Virgen","Pan"], url: "/cantos/src/chtml/s/solaasolo.html"},
    {id:206,title: "Stabat Mater dolorosa", subtitle: "Himno latin", category: "Precatecumenado", moments: ["Cuaresma","Virgen","Pan"], url: "/cantos/src/chtml/s/stabatmaterdolorosa.html"},
    {id:207,title: "Suba el Esposo al leño de su tálamo", subtitle: "Himno (San Quodvultdeus)", category: "Eleccion", moments: [""], url: "/cantos/src/chtml/s/subaelesposoallenodesutalamo.html"},
    {id:208,title: "Sube Dios entre aclamaciones", subtitle: "Sal 47 (46)", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Paz"], url: "/cantos/src/chtml/s/subediosentreaclamaciones.html"},
    {id:209,title: "Te Deum", subtitle: "Himno", category: "Liturgia", moments: ["Laudes"], url: "/cantos/src/chtml/t/tedeum.html"},
    {id:210,title: "Te estoy llamando, Señor", subtitle: "Sal 141 (140)", category: "Precatecumenado", moments: ["Cuaresma","Antiguo Testamento"], url: "/cantos/src/chtml/t/teestoyllamandosenor.html"},
    {id:211,title: "Te he manifestado mi pecado", subtitle: "Sal 32 (31)", category: "Precatecumenado", moments: ["Cuaresma","Antiguo Testamento"], url: "/cantos/src/chtml/t/tehemanifestadomipecado.html"},
    {id:212,title: "Tú eres mi esperanza, Señor", subtitle: "Oda XXIX de Salomón", category: "Catecumenado", moments: ["Adviento","Navidad"], url: "/cantos/src/chtml/t/tueresmiesperanzasenor.html"},
    {id:213,title: "Tú has cubierto de vergüenza la muerte", subtitle: "Homilía Pascual (Melltón de Sardes)", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Virgen","Pan"], url: "/cantos/src/chtml/t/tuhascubiertodevergüenzalamuerte.html"},
    {id:214,title: "Tú que eres fiel", subtitle: "Sal 143 (142)", category: "Precatecumenado", moments: ["Cuaresma","Entrada","Antiguo Testamento"], url: "/cantos/src/chtml/t/tuqueeresfiel.html"},
    {id:215,title: "Un retoño brota del tronco de Jesé", subtitle: "Isaías 11,1-11", category: "Precatecumenado", moments: ["Adviento","Navidad","Pascua","Pentecostés","Comunión","Antiguo Testamento"], url: "/cantos/src/chtml/u/unretonobrotadeltroncodejese.html"},
    {id:216,title: "Una gran señal", subtitle: "Apocalipsis 12", category: "Precatecumenado", moments: ["Adviento","Navidad","Pascua","Pentecostés","Virgen","Nuevo Testamento","Final"], url: "/cantos/src/chtml/u/unagransenal.html"},
    {id:217,title: "Urí, urí, urá", subtitle: "Villancico (Kiko Argüello)", category: "Precatecumenado", moments: ["Adviento","Navidad","Niños"], url: "/cantos/src/chtml/u/uriuriura.html"},
    {id:218,title: "Vamos ya, pastores", subtitle: "Villancico (Kiko Argüello)", category: "Precatecumenado", moments: ["Adviento","Navidad","Niños"], url: "/cantos/src/chtml/v/vamosyapastores.html"},
    {id:219,title: "Ven del Líbano", subtitle: "Cantar de los cantares 4,8ss", category: "Precatecumenado", moments: ["Pascua","Pentecostés","Entrada","Comunión","Antiguo Testamento"], url: "/cantos/src/chtml/v/vendellibano.html"},
    {id:220,title: "Ven, Espíritu Santo", subtitle: "Secuencia de Pentecostés - Himno latin. «Veni, Sancte Spiritus»", category: "Precatecumenado", moments: ["Pascua","Pentecostés"], url: "/cantos/src/chtml/v/venespiritusanto.html"},
    {id:221,title: "Ven, Hijo del Hombre", subtitle: "Apocalipsis 21,17ss", category: "Precatecumenado", moments: ["Adviento","Navidad","Nuevo Testamento"], url: "/cantos/src/chtml/v/venhijodelhombre.html"},
    {id:222,title: "Veni Creator", subtitle: "Himno latin", category: "Precatecumenado", moments: ["Pascua","Pentecostés"], url: "/cantos/src/chtml/v/venicreator.html"},
    {id:223,title: "Viene el Señor", subtitle: "Salmo 93 (92) - Apocalipsis 1,5-7", category: "Precatecumenado", moments: ["Adviento","Navidad","Nuevo Testamento","Antiguo Testamento"], url: "/cantos/src/chtml/v/vieneelsenor.html"},
    {id:224,title: "Virgen de la maravilla", subtitle: "(Dante Allghlerl)", category: "Precatecumenado", moments: ["Adviento","Navidad","Virgen"], url: "/cantos/src/chtml/v/virgendelamaravilla.html"},
    {id:225,title: "Vivid alegres", subtitle: "Filipenses 4,4ss", category: "Precatecumenado", moments: ["Adviento","Navidad","Nuevo Testamento"], url: "/cantos/src/chtml/v/vividalegres.html"},
    {id:226,title: "Vosotros sois la luz del mundo", subtitle: "Mateo 5,14ss ", category: "Precatecumenado", moments: ["Nuevo Testamento"], url: "/cantos/src/chtml/v/vosotrossoislaluzdelmundo.html"},
    {id:227,title: "Ya viene mi Dios", subtitle: "Villancico (Kiko Argüello)", category: "Precatecumenado", moments: ["Adviento","Navidad","Niños"], url: "/cantos/src/chtml/y/yavienemidios.html"},
    {id:228,title: "Yahveh, tú eres mi Dios", subtitle: "Isaías 25,1-8", category: "Precatecumenado", moments: ["Cuaresma","Laudes","Antiguo Testamento"], url: "/cantos/src/chtml/y/yahvehtueresmidios.html"},
    {id:229,title: "Yo te amo, Señor", subtitle: "Sal 18 (17)", category: "Precatecumenado", moments: ["Entrada","Antiguo Testamento"], url: "/cantos/src/chtml/y/yoteamosenor.html"},
    {id:230,title: "Yo vengo a reunir", subtitle: "Isaías 66,18-21", category: "Precatecumenado", moments: ["Entrada","Antiguo Testamento","Final"], url: "/cantos/src/chtml/y/yovengoareunir.html"},
    {id:231,title: "Zaqueo", subtitle: "Lucas 19,1-10", category: "Precatecumenado", moments: ["Cuaresma","Entrada","Laudes","Nuevo Testamento"], url: "/cantos/src/chtml/z/zaqueo.html"},
    {id:232,title: "Prountuario de Acordes", subtitle: "Notas", category: "Catecumenado", moments: [""], url: "/cantos/src/chtml/p/prountuariodeacordes.html"},
    {id:233,title: "Libro de Canto en PDF", subtitle: "Libro de Canto del Camino Neo Catecumenal", category: "Catecumenado", moments: [""], url: "/cantos/src/doc/resucito.pdf", targetBlank: true }
  
    ];