
	// Titulo
	let titulo = "A NADIE DEMOS OCASIÓN DE TROPIEZO";
	let salmo = "2ª Corintios 6,3ss";
	let dbnos = "22";	//Numero del libro

    // Definir variables con la parte de la Asamble
	let Asamblea1 = "HERMANOS, A NADIE DEMOS";
	let Asamblea2 = "OCASIÓN DE TROPIEZO,";
	let Asamblea3 = "HERMANOS, VIVAMOS ACEPTANDO";
	let Asamblea4 = "LAS TRIBULACIONES,";
	let Asamblea5 = "NECESIDADES, ANGUSTIAS Y FATIGAS";
	let Asamblea6 = "HERMANOS, A NADIE DEMOS";
	let Asamblea7 = "OCASIÓN DE TROPIEZO,";
	let Asamblea8 = "HERMANOS, VIVAMOS ACEPTANDO";
	let Asamblea9 = "LAS TRIBULACIONES,";
	let Asamblea10 = "NECESIDADES, ANGUSTIAS Y FATIGAS";
	let Asamblea11 = "HERMANOS, A NADIE DEMOS";
	let Asamblea12 = "OCASIÓN DE TROPIEZO,";
	let Asamblea13 = "HERMANOS, VIVAMOS ACEPTANDO";
	let Asamblea14 = "LAS TRIBULACIONES,";
	let Asamblea15 = "NECESIDADES, ANGUSTIAS Y FATIGAS";
	let Asamblea16 = "HERMANOS, A NADIE DEMOS";
	let Asamblea17 = "OCASIÓN DE TROPIEZO,";
	let Asamblea18 = "HERMANOS, VIVAMOS ACEPTANDO";
	let Asamblea19 = "LAS TRIBULACIONES,";
	let Asamblea20 = "NECESIDADES, ANGUSTIAS Y FATIGAS";

	// Definir variables con la parte del Solista
	let Cantor1 = "Hermanos, a nadie demos ocasión de tropiezo,";
	let Cantor2 = "hermanos, vivamos aceptando las tribulaciones,";
	let Cantor3 = "necesidades, angustias y fatigas;";
	let Cantor4 = "viviendo en pureza, paciencia y bondad;";
	let Cantor5 = "en el Espíritu Santo, y en el poder de Dios;";
	let Cantor6 = "con las armas de la justicia:";
	let Cantor7 = "las de la derecha y las de la izquierda.";
	let Cantor8 = "En calumnias y en buena fama,";
	let Cantor9 = "en gloria e ignominia; como pobres,";
	let Cantor10 = "aunque enriqueciendo a muchos;";
	let Cantor11 = "como quienes nada tienen,";
	let Cantor12 = "aunque lo poseemos todo.";
	let Cantor13 = "¡Hermanos!, os hemos hablado con franqueza;";
	let Cantor14 = "os hemos hablado con la verdad.";
	let Cantor15 = "¡No unciros al yugo desigual con los paganos!";
	let Cantor16 = "¿Qué participación hay entre el fiel y el infiel?";
	let Cantor17 = "¿Qué unión entre el santuario de Dios";
	let Cantor18 = "y el santuario de los ídolos?";
	let Cantor19 = "Porque somos el santuario de Dios.";
	let Cantor20 = "Tengo plena confianza en el hablaros;";
	let Cantor21 = "porque estoy orgulloso de vosotros.";
	let Cantor22 = "¡No unciros al yugo desigual con los paganos!";
	let Cantor23 = "¿Qué participación hay entre el fiel y el infiel?";
	let Cantor24 = "¿Qué unión entre el santuario de Dios";
	let Cantor25 = "y el santuario de los ídolos?";
	let Cantor26 = "En pureza, paciencia y bondad;";
	let Cantor27 = "en el Espíritu Santo, y en el poder de Dios";

    // Asignando variable js a variable html //
    document.getElementById("t1").textContent = titulo;
    document.getElementById("s1").textContent = salmo;
	document.getElementById("dbno").textContent = dbnos;

    document.getElementById("a1").textContent = Asamblea1;
	document.getElementById("a2").textContent = Asamblea2;
	document.getElementById("a3").textContent = Asamblea3;
	document.getElementById("a4").textContent = Asamblea4;
	document.getElementById("a5").textContent = Asamblea5;
	document.getElementById("a6").textContent = Asamblea6;
	document.getElementById("a7").textContent = Asamblea7;
	document.getElementById("a8").textContent = Asamblea8;
	document.getElementById("a9").textContent = Asamblea9;
	document.getElementById("a10").textContent = Asamblea10;
	document.getElementById("a11").textContent = Asamblea11;
	document.getElementById("a12").textContent = Asamblea12;
	document.getElementById("a13").textContent = Asamblea13;
	document.getElementById("a14").textContent = Asamblea14;
	document.getElementById("a15").textContent = Asamblea15;
	document.getElementById("a16").textContent = Asamblea16;
	document.getElementById("a17").textContent = Asamblea17;
	document.getElementById("a18").textContent = Asamblea18;
	document.getElementById("a19").textContent = Asamblea19;
	document.getElementById("a20").textContent = Asamblea20;

	document.getElementById("c1").textContent = Cantor1;
	document.getElementById("c2").textContent = Cantor2;
	document.getElementById("c3").textContent = Cantor3;
	document.getElementById("c4").textContent = Cantor4;
	document.getElementById("c5").textContent = Cantor5;
	document.getElementById("c6").textContent = Cantor6;
	document.getElementById("c7").textContent = Cantor7;
	document.getElementById("c8").textContent = Cantor8;
	document.getElementById("c9").textContent = Cantor9;
	document.getElementById("c10").textContent = Cantor10;
	document.getElementById("c11").textContent = Cantor11;
	document.getElementById("c12").textContent = Cantor12;
	document.getElementById("c13").textContent = Cantor13;
	document.getElementById("c14").textContent = Cantor14;
	document.getElementById("c15").textContent = Cantor15;
	document.getElementById("c16").textContent = Cantor16;
	document.getElementById("c17").textContent = Cantor17;
	document.getElementById("c18").textContent = Cantor18;
	document.getElementById("c19").textContent = Cantor19;
	document.getElementById("c20").textContent = Cantor20;
	document.getElementById("c21").textContent = Cantor21;
	document.getElementById("c22").textContent = Cantor22;
	document.getElementById("c23").textContent = Cantor23;
	document.getElementById("c24").textContent = Cantor24;
	document.getElementById("c25").textContent = Cantor25;
	document.getElementById("c26").textContent = Cantor26;
	document.getElementById("c27").textContent = Cantor27;
